#                           |------------------------------------------------------------|
#                           |        Plugin created by WHiTeG0Dz_ and for support        |
#                           | Contact me on telegram @GodzHardYT or Discord WHiTeG0Dz_#2791|
#                           |------------------------------------------------------------|

#Choose the ping of when a player should be kicked, (I recommend you put it above 2000)
Ping-Kick: 2000

#Choose the kick message when a player is kicked for exceeding the ping limit
Kick-Message: "ยง7You were kicked by the server for: you have exceeded the maximum ping!"

#For my others plugin visit my profile on GitHub! https://github.com/GodzHardYT
